name: rkpm_5
description: Medicine intake tracker
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  go_router: ^14.2.0
  flutter_localizations:
    sdk: flutter
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0


  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  mobx_codegen: ^2.6.0
flutter:
  uses-material-design: true